#include "AWindow.h"

#ifdef OS_Windows
#define BLA a
#endif

#ifdef OS_Linux
#define K_ESC
#define K_F1
#define K_F2
#define K_F3
#define K_F4
#define K_F5
#define K_F6
#define K_F7
#define K_F8
#define K_F9
#define K_F10
#define K_F11
#define K_F12
#define K_CIRC 
#define K_0
#define K_1
#define K_2
#define K_3
#define K_4
#define K_5
#define K_6
#define K_7
#define K_8
#define K_9
#define K_0
#define K_SZ       //TODO Better Name
#define K_HC       //TODO Better Name
#define K_BACKSPACE
#define K_TAB
#define K_Q
#define K_W
#define K_E
#define K_R
#define K_T
#define K_Z
#define K_U
#define K_I
#define K_O
#define K_P
#define K_UE
#define K_PLUS
#define K_ENTER
#define K_CAPSLOCK
#define K_A
#define K_S
#define K_D
#define K_F
#define K_G
#define K_H
#define K_J
#define K_K
#define K_L
#define K_OE
#define K_AE
#define K_HASHTAG
#define K_LSHIFT
#define K_LESS
#define K_Y
#define K_X
#define K_C
#define K_V
#define K_B
#define K_N
#define K_M
#define K_COMMA
#define K_DOT
#define K_MINUS
#define K_LCTRL
#define K_ALT
#define K_SPACEBAR
#define K_CTRLALT
#define K_CONTEXT
#define K_RCTRL
#define K_ROLL
#define K_PAUSE
#define K_INSERT
#define K_POS1
#define K_DEL
#define K_END
#define K_UPWARDS
#define K_DOWNWARDS
#define K_LEFT
#define K_RIGHT
#define K_UP
#define K_DOWN
#define K_NUMLOCK
#define K_NUM_MULT
#define K_NUM_DIV
#define K_NUM_ADD
#define K_NUM_SUB
#define K_NUM_ENT
#define K_NUM_COMMA
#define K_NUM_1
#define K_NUM_2
#define K_NUM_3
#define K_NUM_4
#define K_NUM_5
#define K_NUM_6
#define K_NUM_7
#define K_NUM_8
#define K_NUM_9
#define K_NUM_0
#endif